services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: change_this_securely

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    depends_on:
      - postgres
    ports:
      - "18080:8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: change_this_securely
      # KC_HOSTNAME: keycloak.yourdomain.com  # ← optional if behind FRP
      KC_BOOTSTRAP_ADMIN_USERNAME: admin  # change the admin password once started
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin  # change the admin password once started
    command: start-dev
    # command start # start a development server
    restart: unless-stopped

volumes:
  keycloak_postgres_data:
