name: keycloak

services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - keycloak_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: change_this_securely

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.0
    depends_on:
      - postgres
    ports:
      - "18443:8443"
    volumes:
      - /etc/letsencrypt/live/ziangren.com/fullchain.pem:/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/ziangren.com/privkey.pem:/certs/privkey.pem:ro
    environment:
      # connection
      KC_HOSTNAME: auth.ziangren.com
      KC_HOSTNAME_STRICT: true
      KC_HOSTNAME_STRICT_HTTPS: true
      # tls certificats
      KC_HTTPS_CERTIFICATE_FILE: /certs/fullchain.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /certs/privkey.pem

      # database
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: change_this_securely
      # health and metrics
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true

      # bootstrap admin user
      KC_BOOTSTRAP_ADMIN_USERNAME: admin  # change the admin password once started
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin  # change the admin password once started
    command: start
    # command start # start a development server
    restart: unless-stopped

volumes:
  keycloak_postgres_data:
