name: vault
services:
  vault:
    image: hashicorp/vault:latest
    hostname: vault
    ports: ["38200:8200"]
    cap_add: ["IPC_LOCK"]
    environment:
      VAULT_ADDR: https://vault:8200
      VAULT_LOG_LEVEL: info
    volumes:
      - vault_data:/vault/file
      - ./tls:/tls:ro        # ca.pem, server.crt, server.key
    command: >
      server -config=/vault/file/vault.hcl
networks:
  vault-net:
volumes:
  vault_data:
